[package]
name = "rscoop"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-lapper = "1.1.0"
clap = { version = "4.4.0", features = ["derive"], optional = true }

[features]
binary = ["clap"]

[[bin]]
name = "rscoop"
path = "src/main.rs"

